First feature branch with migrations.
BrentFarese/JuristatApp pull request #1
Opened 2017-05-24 13:59 UTC by BrentFarese

2017-05-24 14:01 UTC, fugufish commented on migrations/20170524131128-initial_migration.js
> +
We need to make sure to add indexes!

2017-05-25 19:47 UTC, fugufish requested changes

2017-05-25 19:47 UTC, fugufish commented on migrations/20170524131128-initial_migration.js
> +        applicationId: {
foreign keys should always be indexed.

2017-05-26 01:37 UTC, BrentFarese commented on migrations/20170524131128-initial_migration.js
> +        applicationId: {
Will add these and will be in the next commit.  Thanks!

2017-05-26 01:37 UTC, BrentFarese reviewed
Will add foreign key indexes in next commit.

2017-05-26 13:14 UTC, closed without merging